asurgent/ui

src/Button/Button.js
src/Button/Button.stories.js
src/Button/Button.styled.js
src/Button/helper.js
src/Modal/Modal.styled.js
src/Shield/Shield.styled.js
src/Table/BaseTable/BaseTable.js
src/Table/BaseTable/BaseTable.styled.js
src/Table/MainTable/MainTable.js
src/Table/MainTable/MainTable.styled.js
src/Table/Table.stories.js
src/Table/TableControlls/TableControlls.js
src/Table/useTableHook.js

Created an extession to the button component so that you can pass an object/string/promise that will get downloaded with the JSON extenssion.
This button was then implemented on the table-component so that a user can export their search results from azure-search.
Run storybook:

List export functionallity

---

src/Form/hooks/useFormBuilder.js
src/Table/TableSearchBar/TableSearchBar.js
src/Table/TableSearchBar/TableSearchBar.styled.js

The search bar did not receive auto focus when mounting (actually it did for a split second but the focus-status got overwritten).
Fixes #829

Fix for searchbar not receiving auto focus

---

src/Table/TableFilter/components/FilterCategory.js
src/Table/TableFilter/components/FilterCategory.styled.js
src/Table/TableFilter/helpers.js
src/Transition/Transition.stories.js
src/Transition/Transition.styled.js
src/Transition/index.js

Solving the following issues was done with two small changes. But while at it i noticed other issues we had with the `FilterCategory` component, so I refactored the HTML/CSS structure and started adding JSDoc comments in some palaces.
The last change is that i created and changed was `FadeInSlideDownOnDesktop` transition for the filters. This because wanting to position the dropdown filter with the `fixed` attribute on mobile. This is needed because `translation` creating a new coordinate system and thereby makes fixed impossible to use if you want it to cover the entire screen. More can be read here https://stackoverflow.com/questions/53251782/how-to-put-fixed-element-inside-transformed-container
Fixes https://github.com/asurgent/admin/issues/828
Fixes …

Autofocus and refactor table-filters

---

src/Button/Button.stories.js
src/Button/Button.styled.js
src/Button/index.js
src/Form/types/Select.js
src/Form/types/Text.js
src/Form/types/TextArea.js
src/Switch/Switch.js
src/layout/Layout/Layout.js

Fix issues with prop-types and other warnings thrown in from the portal
Make sure the tests pass.
- [ x The documentation is sufficinent 
- [x ] The tests runs withour errors and covers all/most states/scenarios

Prop-type fixes

---

src/Button/Button.js
src/Button/Button.stories.js
src/Button/Button.styled.js
src/Button/index.js

Add `type` prop to button and add ability to cast button to native webb button with type `submit`. This is needed in forms that are constructed with formik.
- Go to the button section in Storybook
- Open `Submit button` story.
- Click the button and look in `actions` console to see the submit-logged.
- [ X My changes generate no new warnings

Add ability to "cast" button to a native web button.

---

src/Block/Block.stories.js
src/Block/Block.styled.js
src/Block/BlockStatusMessage.js
src/Block/index.js
src/Form/Form.stories.js
src/Form/types/DatePicker.styled.js

Need a new block with the blue theme to wrap the form component on Alert Rules.

blue themed block for usage on alert rule form

---

src/Table/BaseTable/BaseTable.styled.js

Add left/right padding to base-table count row
- Look at base-table component count row

Add left/right padding to base-table count row

---

.eslintrc.js
jest.config.js
package-lock.json
package.json
src/Block/Block.test.js
src/Button/Button.test.js
src/Tag/Tag.test.js
src/Tooltip/ToolTip.test.js
test-utils/index.js
webpack.config.js

Clean things up and move test-utils to root folder and add an alias t…o target the folder
Test should run successfully 
- [] I have commented my code, particularly in hard-to-understand areas

Adjust testing configuration

---

src/Tooltip/Tooltip.js
src/Tooltip/Tooltip.stories.js
src/Tooltip/Tooltip.styled.js
src/Tooltip/index.js

Refactor tooltip some and add `left` orientation as an option.
- Run storybook `Tooltip` left option

Add left orientation to tooltip

---

src/Tag/Tag.stories.js
src/Tag/components/Tag.js
src/Tag/components/Tag.styled.js
src/Tag/components/TagCollection.js
src/Tooltip/Tooltip.js
src/Tooltip/Tooltip.stories.js
src/Tooltip/Tooltip.styled.js
src/Tooltip/index.js

Some previous changes must have broken these. Now the `X` shows again .
- Look at storybook for `Tags.Collection`

Fix tags delete action

---

src/Modal/Modal.js
src/Modal/Modal.stories.js
src/Modal/Modal.styled.js
src/Modal/index.js

Ability to make modal fullscreen  and have correct positioned `Actionbar` (buttons in bottom of modal)
- Run modal storybook and adjust knobs. Fullscrren will only show if you run it in its own window.

Modal updates 

---

src/Table/MainTable/MainTable.js
src/Table/Table.stories.js
src/Table/TableFilter/TableFilter.translation.js
src/Table/TableFilter/components/FilterCategory.js
src/Table/TableFilter/components/FilterItem.js
src/Table/TableFilter/components/TableFilter.js

Make it possible to trigger callback when a filter is changed/added/removed
- Run `Table.Filter` story and look in actions console when changing `Guys` filter for `OnChange` action.

Add Table filter callbacks

---

src/Moment/Moment.stories.js
src/Moment/Moment.translation.js
src/Moment/MomentDuration.js
src/Moment/index.js

Add duration alternative to moment component
- Run `Moment.Duration` in storybook

Moment duration

---

src/Form/Form.js
src/Form/Form.stories.js
src/Form/hooks/useFormBuilder.js

Need to be able to hide/show some fields depending on other fields values (such as clicking the radio button "Indefinately" on alert rules should hide the datepicker), so we're adding support for this to the form component of the UI lib.
Fixes: https://github.com/asurgent/admin/issues/886
Related to: https://github.com/asurgent/admin/issues/856
- [ ] Check that it reappears when shortening the text input again.

Render-prop for form fields

---

src/Form/hooks/useFormBuilder.js

Fix form to support form specs from API
- Run form-api storybook

Fix form fatal

---

.github/workflows/build.yml
.github/workflows/delete.yml

Renamed stuff

---

.github/workflows/delete.yml
.github/workflows/test.yml

Kefa test pr build

---

.github/workflows/build.yml

Added comments to PR

---

.github/workflows/build.yml

This reverts commit b02d97e947b1401176281e0ec7a14c4991680a35.

Revert "Moved first comment to first job"

---

src/Form/types/RadioGroup/RadioGroup.styled.js

alignment was off on radios with wrapped labels

---

src/Table/Table.stories.js
src/Table/TableFilter/TableFilter.translation.js
src/Table/TableFilter/components/FilterCategory.js
src/Table/TableFilter/components/FilterItem.js
src/Table/TableFilter/components/FilterItem.styled.js
src/Table/TableFilter/components/TableFilter.js
src/Table/TableFilter/useFilterHook.js
src/Table/TableFilter/useFilterItemHook.js

Adding a count to filters where applicable, also making the full row clickable
Fixes https://github.com/asurgent/admin/issues/909
- [x ] I have performed a self-review of my own code

Ofriberg add count to filter

---

.github/workflows/build.yml
.github/workflows/delete.yml

Github workflow update
asurgent/admin#926

Use fork instead of directly using the latest commit of a public repo

---

src/Dismissable/Dismissable.js
src/Dismissable/Dismissable.stories.js
src/Dismissable/Dismissable.styled.js
src/Dismissable/index.js
src/Transition/Transition.stories.js
src/Transition/Transition.styled.js
src/Transition/index.js
src/index.js

Since we are using dismissable windows on several places (and are probably going to use them even more), we want to have it as a component in the UI-library.
Fixes https://github.com/asurgent/admin/issues/925

dismissable information windows

---

src/TimeComponents/components/DateSpan/DateSpan.js
src/TimeComponents/components/Duration/Duration.js
src/TimeComponents/components/NextDate/NextDate.js
src/TimeComponents/components/Repeat/Repeat.js
src/TimeComponents/components/StartEnd/StartEnd.js
src/Transition/Transition.styled.js

Accept extra props (style) on the TimeComponents. Also removed the z-index for Transition.FadeInSlideDown which doesnt seem to do anything, but messes up the page on Service Windows (is infront of the search bar)

Pass extra props to timecomponents

---

src/Form/Form.stories.js
src/Form/helpers.js
src/Form/hooks/useFormBuilder.js
src/Form/types/FilterSelect/FilterSelect.js
src/Form/types/FilterSelect/FilterSelect.styled.js
src/Form/types/FilterSelect/components/FilterSelectItem.js
src/Form/types/FilterSelect/components/FilterSelectItem.styled.js
src/Form/types/FilterSelect/useFilterSelectHook.js

Refactor and reimplement multi-select form component.
Fixes https://github.com/asurgent/admin/issues/969

Multi select component

---

src/Form/Form.js
src/Form/Form.stories.js

removed it last week, thought it wasn't needed anymore, but still is, so putting it back in there

Put back the setTimeout on eventTrigger (form)

---

src/Button/Button.stories.js
src/Spinner/Spinner.js
src/Spinner/Spinner.stories.js
src/Spinner/Spinner.styled.js

Make the default spinner color asurgent-blue instead of black

blue as default spinner color

---

src/Form/types/RadioGroup/RadioGroup.styled.js

radio group right margin

---

src/Form/Form.js
src/Form/Form.stories.js
src/Form/hooks/useFormBuilder.js
src/Form/types/DatePicker/DatePicker.js
src/Form/types/FilterSelect/FilterSelect.js
src/Form/types/Number/Number.js
src/Form/types/RadioGroup/RadioGroup.js
src/Form/types/Select/Select.js
src/Form/types/Text/Text.js

When changing something in props of a form type - for example changing the options of a select - it resets the value of all the other fields since all the form types updates the value when anything in the prop-changes, not prop.values (which triggers even though nothing seems to actually change)
useEffect(() => {
setValue(props.value || '');
}, [props]);
Should change to only update the value when prop.value changes.
(Check issue for pics)
Fixes https://github.com/asurgent/admin/issues/1006

changing something in the prop of fields resets the value

---

src/Form/Form.js
src/Form/Form.stories.js
src/Table/TableFilter/components/FilterCategory.js
src/Table/TableFilter/useFilterGroupHook.js
src/Table/TableSearchBar/TableSearchBar.js
src/Table/TableSort/TableSort.js

Fixes so form will trigger and work properly on all callbacks
- Try the table components, like search-bar and filter-selects and make sure the inputs trigger and work properly

Fixes for form

---

src/Progress/Progress.stories.js
src/Progress/components/Ring/Ring.js
src/Progress/components/Ring/Ring.styled.js
src/Progress/components/Ring/index.js
src/Progress/index.js
src/index.js

Need a progress component (ring) for service windows
Fixes https://github.com/asurgent/admin/issues/1015

Create a progress component

---

src/Block/Block.stories.js
src/Block/SubnavigationBlock.js
src/Block/SubnavigationBlock.styled.js

Build Subnavigation block with grids instead and make it look okay-ish on mobile.
- Open http://localhost:6006/iframe.html?id=ui-components-block--subnavigation-block
- Run it in mobile and regular desktop
- Max-width on content to 1010px

Subnavigation Block Refactor

---

lib/style/theme.js
src/TimeComponents/TimeComponents.stories.js
src/TimeComponents/TimeComponents.styled.js
src/TimeComponents/components/DateSpan/DateSpan.js
src/TimeComponents/components/Icons.js
src/TimeComponents/components/StartEnd/StartEnd.js

Just some UI & translation fixes for timecomponents

ui & translation fixes for timecomponents

---

src/TimeComponents/TimeComponents.styled.js
src/TimeComponents/components/DateSpan/DateSpan.js
src/TimeComponents/components/Repeat/Repeat.js
src/TimeComponents/components/StartEnd/StartEnd.js

more ui changes for timecomponents

---

package-lock.json
package.json
src/Markdown/Markdown.js
src/Markdown/Markdown.stories.js
src/Markdown/Markdown.styled.js
src/Markdown/exampleMarkdown.md
src/Markdown/index.js
src/index.js

Create a markdown component for the UI-lib that can be used in the portal project
Fixes https://github.com/asurgent/admin/issues/1022
- [ ] (optional: Wrap the Markdown-component in a div that gives for example tables some styling/add some CSS to Markdown.styled.js)

Create a markdown component

---

src/Form/Form.stories.js
src/Form/components/InputWrapper.styled.js
src/Form/types/FilterSelect/FilterSelect.styled.js
src/Form/types/RadioGroup/RadioGroup.styled.js

Fixes https://github.com/asurgent/admin/issues/1024

Fix overflow issues on form types (mostly on small devices)

---

src/Block/Block.stories.js
src/Block/components/SubnavigationBlock/SubnavigationBlock.js

Ability to override and style subnavigation items
- Go to `Block`->`SubnavigationBlock` and see that the top navigation-item has wacky styling, this is because you now can override styling on each element of the navigation-items

Ability to override and style subnavigation items

---

src/Truncate/Truncate.js
src/Truncate/Truncate.stories.js
src/Truncate/helpers.js
src/Truncate/index.js
src/index.js

Create a truncate component for usage in the portal in various places
- http://localhost:6006/?path=/story/ui-components-truncate--start
- http://localhost:6006/?path=/story/ui-components-truncate--center
- http://localhost:6006/?path=/story/ui-components-truncate--end
and change the string input and max length and check that it works as expected

truncate string component

---

src/Button/Button.styled.js
src/Table/BaseTable/BaseTable.js
src/Table/TableSearchBar/TableSearchBar.styled.js
src/layout/Layout/Layout.styled.js

Spinner color on table, fix filter buttons, fix login button, re-added search icon and changed logo to be blue on white background on mobile for a cleaner look.

Small fixes and styling

---

src/Button/Button.js
src/Tooltip/Tooltip.js
src/Tooltip/Tooltip.styled.js
src/Tooltip/index.js

Last push for tooltips messed up buttons without tooltips, fix for that

Button fix

---

src/TimeComponents/TimeComponents.stories.js
src/TimeComponents/components/Repeat/Repeat.js
src/TimeComponents/components/Repeat/Repeat.translation.js

cron_category == null shows as "repeatnullShort", fix it so it shows "occurs once"
Fixes https://github.com/asurgent/admin/issues/1063

handle croncategory === null

---

src/Form/Form.stories.js
src/Form/hooks/helpers.js
src/Form/types/TextMultiple/TextMultiple.js
src/Form/types/TextMultiple/TextMultiple.styled.js
src/Form/types/TextMultiple/index.js

Need a form type that takes multiple text inputs, new component for that

Multiple text input type (pass array of strings)

---

src/Button/Button.js
src/Button/Button.stories.js

Ability to pass style-attr to button-components
- Go to Button -> Accept Button. It has crazy padding trough style-attr

Ability to pass style-attr to button-components

---

src/List/List.js
src/List/List.stories.js
src/List/helpers.js

Fix for 0 evaluating as N/A on List component
Fixes https://github.com/asurgent/admin/issues/1097

0 renders as n/a in list component

---

src/Button/Button.js
src/Button/Button.stories.js
src/Button/helper.js
src/Table/BaseTable/BaseTable.js
src/Table/Table.stories.js

Add option to export as csv, and set it to default.
Fixes https://github.com/asurgent/admin/issues/1078

Save to CSV

---

src/Shield/Shield.styled.js
src/Tooltip/Tooltip.styled.js
src/Transition/Transition.styled.js
src/layout/Omnibar/Omnibar.styled.js

Fix z-index issues
Run in portal

Adjust z-index issues

---

src/Progress/Progress.stories.js
src/Progress/components/Bar/Bar.js
src/Progress/components/Bar/Bar.styled.js
src/Progress/components/Bar/index.js
src/Progress/index.js

Need to extend the progress-component with a bar-type, that looks like:
Fixes https://github.com/asurgent/admin/issues/1159

vertical (bar) progress bar

---

src/Form/Form.stories.js
src/Form/types/Select/Select.js

change optionDisabled propname to disabled on selects

---

src/Modal/Modal.styled.js
src/Shield/Shield.styled.js
src/Table/TableFilter/components/FilterCategory.js
src/Table/TableFilter/components/FilterCategory.styled.js
src/Toasts/components/ToastManager/ToastManager.styled.js
src/Tooltip/Tooltip.styled.js
src/Transition/Transition.styled.js
src/layout/Omnibar/Omnibar.styled.js

* Fix z-index
* Fix filter-category issue that you were able to click the filter-button when the filter-list was open. That caused unnecessary reloads of data.

Z-Index issues

---

src/Table/TableSort/TableSort.styled.js

Fixed sort field in omnibar looking weird in smaller size window

---

src/Table/BaseTable/BaseTable.styled.js

Always show export button/icon on tables
Fixes https://github.com/asurgent/admin/issues/1151

show export button by default

---

src/Block/Block.stories.js
src/Block/components/SubnavigationBlock/SubnavigationBlock.js
src/Block/components/SubnavigationBlock/SubnavigationBlock.styled.js
src/Button/Button.js
src/Button/index.js

Button url state keeping

---

src/Table/TableFilter/components/FilterCategory.js
src/Table/TableFilter/components/FilterCategory.styled.js
src/Table/TableFilter/useFilterGroupHook.js

Styled Mikael's active state on filter with a blue underline when a filter is active as shown in image below.
Fixes asurgent/admin#1095

Miha active state on filter

---

package-lock.json
src/Block/components/SubnavigationBlock/SubnavigationBlock.styled.js
src/Button/Button.styled.js
src/Form/components/InputWrapper.styled.js
src/List/List.styled.js
src/layout/DropdownMenu/DropdownMenu.styled.js
src/layout/Layout/Layout.styled.js
src/layout/Navigation/Navigation.styled.js

A few minor fixes such as z-index bug, list alignment, form element width bug and touch up on sub navigation.
Fixes asurgent/admin#1161
Fixed z-index bug, see image

Tojo minor fixes

---

package.json
src/Block/components/SubnavigationBlock/SubnavigationBlock.js
src/Button/Button.js
src/Button/helper.js
src/Table/BaseTable/helpers.js
src/Table/useTableHook.js
src/Tooltip/Tooltip.js
src/Tooltip/Tooltip.styled.js

Add logic to to button that keeps track of the search state keys of the url

Button clear history state

---

src/Graph/Heatmap/Heatmap.styled.js

Made them identical in style for consistency.

Made heatmap tooltip look like regular tooltip

---

lib/style/theme.js
src/Block/components/Accordion/Accordion.styled.js
src/Form/types/DatePicker/DatePickerThemeProvider.js
src/TimeComponents/TimeComponents.styled.js
src/Toasts/Toasts.stories.js
src/Toasts/components/Toast/Toast.js
src/Toasts/components/Toast/Toast.styled.js
src/Toasts/components/ToastManager/ToastManager.styled.js
src/layout/DropdownCreate/DropdownCreate.styled.js

Color updates. 
Spacing fixes on Accordion. 
Datepicker color update. 
Toast tweaks.
Fixes asurgent/admin#1144

Tojo fixes

---

src/Block/components/Accordion/Accordion.js
src/Button/Button.styled.js
src/Button/index.js
src/Dismissable/Dismissable.js
src/Form/components/InputWrapper.js
src/Form/types/FilterSelect/FilterSelect.js
src/Form/types/FilterSelect/components/FilterSelectItem.js
src/Form/types/ObjectInput/Multiple/Multiple.js
src/Form/types/Select/Select.js
src/Form/types/TextMultiple/TextMultiple.js
src/Modal/Modal.js
src/Table/BaseTable/BaseTable.js
src/Table/TableFilter/components/FilterCategory.js
src/Table/TableFilter/components/FilterItem.js
src/Table/TableFilter/components/TableFilter.js
src/Table/TablePagination/TablePagination.js
src/Table/TableSearchBar/TableSearchBar.styled.js
src/Table/TableSort/TableSort.js
src/Tag/components/Tag.js
src/TimeComponents/components/StartEnd/StartEnd.js
src/Toasts/components/Toast/Toast.js
src/layout/CurrentUser/CurrentUser.js
src/layout/DropdownCreate/DropdownCreate.js
src/layout/DropdownMenu/DropdownMenu.js
src/layout/DropdownMenu/DropdownMenu.styled.js
src/layout/Layout/Layout.js

Updated icon sizes. 
Fixed toast not closing on click. 
Added focus/active state on search bar.

Icon updates

---

src/Modal/Modal.styled.js
src/Table/TableFilter/components/FilterCategory.styled.js
src/Table/TableFilter/components/TableFilter.styled.js
src/Toasts/components/ToastManager/ToastManager.js
src/Tooltip/Tooltip.styled.js
src/Transition/Transition.styled.js
src/layout/Layout/Layout.styled.js
src/layout/Omnibar/Omnibar.styled.js

Resolve a bunch of z-index issues

---

src/TimeComponents/components/Repeat/helpers.js

Make sure that the percentage cant be higher than 100 and lower than 0
Fixes https://github.com/asurgent/admin/issues/1147

Fix min and max values of percentage

---

src/Graph/Graph.stories.js
src/Graph/Heatmap/Heatmap.js
src/Graph/Heatmap/components/Squares/Squares.js

Heatmap crashes on year-change partly due to "today" placement (when the graph doesnt have today in it), fix for that.
Fixes https://github.com/asurgent/admin/issues/1234

Fatal bug on year change

---

lib/style/theme.js
src/Cron/CronEditor.styled.js
src/Table/BaseTable/BaseTable.js
src/Table/BaseTable/BaseTable.styled.js
src/Table/BaseTable/BaseTable.translation.js
src/Table/BaseTable/helpers.js
src/Table/MainTable/MainTable.js
src/Table/Table.stories.js
src/Tooltip/Tooltip.stories.js
src/Tooltip/Tooltip.styled.js
src/Tooltip/helpers.js
src/Typography/Typography.Paragraphs.styled.js
src/Typography/Typography.stories.js

Related to: https://github.com/asurgent/admin/issues/1183
https://github.com/asurgent/cloudops-portal/pull/206

Optional keep track of added/removed table rows + some css changes

---

src/Button/Button.js
src/Permission/Permission.stories.js
src/Table/Table.stories.js
src/Tooltip/Tooltip.js
src/Tooltip/Tooltip.stories.js
src/Tooltip/cards/Entity/EntityTooltipCard.js
src/Tooltip/cards/Entity/EntityTooltipCard.styled.js
src/Tooltip/cards/Entity/EntityTooltipCard.translation.js
src/Tooltip/cards/Entity/index.js
src/Tooltip/cards/index.js
src/Tooltip/hoc/withAllPositions.js
src/Tooltip/index.js

Move entity-tooltip into UI library
- View tooltip storybook

Create tooltip card for entity

---

src/Table/Table.stories.js
src/Table/TableFilter/helpers.js
src/Table/TableFilter/useFilterGroupHook.js
src/Table/TableFilter/useFilterHook.js
src/Table/TableFilter/useFilterItemHook.js

Run Table-Filter in storybook make sure the guys-filter returns `custom_operator` as the operator of the catrgory

Add ability to set custom operator for table filers categories

---

src/layout/DropdownCreate/DropdownCreate.js

Added a link prop so that the buttons in DropdownMenuCreate can redirect if needed, not just run a passed function
Related to: https://github.com/asurgent/cloudops-portal/pull/212

Optional link prop to DropdownMenuCreate

---

src/Selector/Selector.js
src/Selector/Selector.styled.js

Just a minifix for text color on selected

small selector colorfix on selected

---

src/Button/index.js
src/Table/MainTable/MainTable.js
src/Table/TableFilter/components/FilterCategory.js
src/layout/DropdownCreate/DropdownCreate.styled.js
src/layout/Omnibar/Omnibar.styled.js

Cleaned up some colors and spinner ring sizes.

Cleaned up some colors and spinner ring sizes.

---

src/Graph/Graph.stories.js
src/Graph/PlainLineGraph/PlainLineGraph.js
src/Graph/PlainLineGraph/PlainLineGraph.styled.js
src/Graph/PlainLineGraph/PlainLineGraph.translation.js
src/Graph/PlainLineGraph/index.js
src/Graph/components/Canvas/useChartDimensions.js
src/Graph/components/MarkerLine/MarkerLine.js
src/Graph/index.js

Update useDimensions hook so during implementation can define width and height. If its not defined it will autoresize to its parent.
- New implementation of graph
- http://localhost:6006/iframe.html?id=ui-components-graph--plain-graph
- Make sure old graph still works

Create plain line graph and adjust dimensions-hook

---

package-lock.json
package.json

bump asurgent-eslint-config

---

src/Table/BaseTable/BaseTable.js
src/Table/BaseTable/BaseTable.styled.js

Fixes https://github.com/asurgent/admin/issues/1244

Fix download icon becoming too small on large results

---

src/ImagePreview/ImagePreview.js
src/ImagePreview/ImagePreview.stories.js
src/ImagePreview/ImagePreview.styled.js
src/ImagePreview/index.js
src/index.js

Move image preview-component (Screenshot in portal), to UI proj.

Image preview component

---

src/Graph/Heatmap.stories.js
src/Graph/Heatmap/Heatmap.js
src/Graph/Heatmap/components/Squares/Squares.js

Fixes https://github.com/asurgent/admin/issues/1264

Heatmap fix for "today"-square if only successes

---

src/Table/useTableHook.js

Related to: https://github.com/asurgent/admin/issues/1263

Fix filter payload in export table results

---

src/Table/Table.stories.js
src/Table/TableFilter/useFilterGroupHook.js
src/Table/TableFilter/useFilterHook.js
src/Table/useTableHook.js
src/layout/Layout/Layout.stories.js

Pass filter state to update-trigger function
Relates to https://github.com/asurgent/admin/issues/1060
Go to table-filter story:
http://localhost:6006/?path=/story/data-table--filter
Open and select some values from the filters and look at the console. We now can se what the state is uncompiled and what filter that is being opened.

Table: Pass filter state to update-trigger function

---

src/layout/DropdownMenu/DropdownMenu.js
src/layout/DropdownMenu/DropdownMenu.styled.js
src/layout/Layout/Layout.js
src/layout/Layout/Layout.stories.js
src/layout/Navigation/Navigation.js
src/layout/Navigation/Navigation.styled.js

Navigation option for dropdown menu on desktop
Related to https://github.com/asurgent/admin/issues/1118

Desktop dropdown navigation (my team)

---

src/Tag/components/Tag.styled.js

Tag overflow-fix

---

src/Table/useTableHook.js

Add some API functions to the table-hook

Make table compatible with react-query

---

package-lock.json
src/Form/Form.stories.js
src/Form/types/TextArea/TextArea.js

Fix for textareas not validating/showing errors.

Textarea validation/show errors fix

---

package-lock.json
src/Block/Block.stories.js
src/Block/components/BlockStatusMessage/BlockStatusMessage.js
src/Block/components/BlockStatusMessage/BlockStatusMessage.styled.js

Just making the stateblocks a little bit less in your face
From: 
To:

Little bit more discrete stateblocks
