asurgent/ui

- src/Table/Table.stories.js
- src/Table/TableFilter/useFilterHook.js
When the filter read its state from the url, eg after reloading the page, the table component lost some of its state and the `clear filter` button wouldn't show up until you altered the table-filter-state again.
Fixes https://github.com/asurgent/admin/issues/823
- Run storybook, go to `Table/Main` story.
- Set a filter & make sure the `clear filter` button appears.
- Reload page.
- The `clear filter` button should still be there.
- Now clear the filter by clicking the button.
- Open the `Guys` filter and make sure an option is selected, even tough the clear filter button is not visible. This is the correct behaviour for a single-select filter-category.
> Show clear filter button

- src/Loader/Loader.js
- src/Loader/Loader.stories.js
- src/Loader/Loader.styled.js
- src/Loader/index.js
- src/index.js
The React-Spinners-Kit that we use for our loader-component is using animation with box-shadow and the inset property, which is not working as it should on Safari (a lot of flickering). So instead we created our own component that animates a clip-path instead. After this we can remove the old one and replace all uses of that one with this one.
Fixes https://github.com/asurgent/admin/issues/839
Relates to https://github.com/asurgent/admin/issues/830
> Make a new loader component, prepare for removing the old one.

- src/Form/Form.stories.js
- src/Form/types/DatePicker.js
- src/Form/types/Label.js
- src/Form/types/RadioGroup.js
- src/Form/types/RadioGroup.styled.js
- src/Form/types/Select.js
- src/Form/types/Text.js
- src/Form/types/Text.styled.js
- src/Form/types/TextArea.js
Radiogroup had a bug in that it could not differentiate between two radiogroups if they both had the same options (since it leads to the inputs having the same name). Fix for that. Also added a header similar to other input types.
> radio group fix

- src/Form/Form.js
- src/Form/Form.stories.js
Return `isDirty` as a state in child-render instead of object, since that wont trigger a redraw
- Run `Form - Default form` storybook
- Change from data
- Reset-button should toggle between disabled and enabled when clicked/form-change
> Form isDirty as state

- src/Cron/CronEditor.js
- src/Cron/CronEditor.styled.js
- src/Cron/components/Occurrence.js
- src/Cron/useCronHook.js
Handle the use case when the user empties the input-filed for start & end -date. This is currently causing fatal crash
- Run storybook for `Cron`
- Empty start-date field
- Select end on date and empty that as well
- Try different combinations
- Payload should return `valid: false`
- X ] My changes generate no new warnings
> Cron: Start & End date fix

- .storybook/decorators/i18nDecorator.js
- lib/i18n/addTranslation.js
- lib/i18n/findTranslations.js
- src/Form/Form.js
- src/Form/Form.stories.js
- src/Form/Formstories.translation.js
- src/Form/components/InputWrapper.styled.js
- src/Form/hooks/useFormBuilder.js
- src/layout/DropdownCreate/DropdownCreate.styled.js
Change how we construct the translation key objects. Previously we added a underscore between the translation id and key. I simply removed the underscore since it didn't really give us anything.
This helped us to make it easier to create translations for form-validation errors, since we simply can pass the ID or if we want the entire translation object returned from addTranslation.js
- Cant be tested in the portal other than making sure that all translations work as expected still.
- Check that error-labels render in `Default Form story `
> Form error-list & translation fixes

- src/Form/types/RadioGroup/RadioGroup.styled.js
radios inherit width:100% from general input-css that overwrites the radio's css, so the radiolabel wraps even though it doesnt have to. fix for that
> css fix for radios

- src/Form/Form.stories.js
- src/Form/Formstories.translation.js
- src/Form/helpers.js
- src/Form/hooks/useFormBuilder.js
- src/Form/types/Number.js
Needed a new number input type so that we dont have to parse it back and forth when using the text type
Fixes # https://github.com/asurgent/admin/issues/913
And resetting the form should work.
> Number form type-component

- src/Tooltip/Tooltip.stories.js
- src/Tooltip/Tooltip.styled.js
Make tooltips respect linebreaks in texts, and make them look more like the popover-tooltips we had on Alert Rules-page
Fixes # https://github.com/asurgent/admin/issues/918
In storybook:
> tooltip - linebreaks and colors

- src/Block/Block.styled.js
- src/Tooltip/Tooltip.styled.js
tooltip back to black and fix so that it doesnt overflow the screen, and removed block from adding colors
> tooltipfix, and removed block from adding colors

- src/Table/TableFilter/components/FilterItem.js
- src/Table/TableFilter/components/FilterItem.styled.js
Remove possibility to add the categories themselves to the filter, only entries should be clickable.
Fixes https://github.com/asurgent/admin/issues/939
> disable categories from being selectable

- src/Table/BaseTable/BaseTable.js
- src/Table/BaseTable/BaseTable.styled.js
- src/Table/BaseTable/helpers.js
- src/Table/Table.stories.js
- src/TimeComponents/components/Duration/Duration.js
- src/TimeComponents/components/Duration/Duration.translation.js
Need to be able to override the card component's standard CSS for some purposes, a fix for that. Plus a tiny translation fix.
Related to https://github.com/asurgent/admin/issues/958
> override for cardcontainers & translation-fix

- src/Table/TableSearchBar/useSearchbarHook.js
Encode/encode search-string so i doesn't get cleaned  up bu the broser on refresh
Fixes https://github.com/asurgent/admin/issues/942
- Run saga locally or use the hosted version
- Go to http://localhost:6006/iframe.html?id=ui-components-table--main&tickets_q=%2522Test%2522%2520%2522%253A%252F%252F%2522%20
- The search-string the the table should be `"Test" "://" `
> Perserve search-state for tables

- src/Block/Block.stories.js
- src/Button/Button.js
- src/Button/Button.stories.js
- src/Form/Form.js
- src/Form/Form.stories.js
- src/Form/Form.test.js
- src/Form/hooks/useFormBuilder.js
If a form field still has focus you cant submit the form (or click cancel/reset) without blurring the field first. So for example clicking on a radio button, you have to click somewhere else first before being able to click on the form buttons. Fix for that. 
Fixes https://github.com/asurgent/admin/issues/985
> Cant submit form without bluring fields first

- package-lock.json
- src/Form/Form.stories.js
- src/Form/types/Select/Select.js
Need to have an option for the select type to not automatically add the first option as selected by default.
> option for not adding the first option as default on select

- src/Markdown/Markdown.js
- src/Markdown/exampleMarkdown.md
- src/Markdown/helpers.js
Add whitelist to markdown component, and expand it with code/pre.
Fixes https://github.com/asurgent/admin/issues/1005
> markdown whitelist

- src/Tag/Tag.stories.js
- src/Tag/components/Tag.js
- src/Tag/components/Tag.styled.js
- src/Tag/components/TagCollection.js
- src/Tooltip/Tooltip.stories.js
Fix tag overflow, max string length for tags in collections, and renaming of props (both single and collection had a prop named max but meant different things, string length in one and max tags in one -> maxLength, maxTags).
> fix for tag overflow & max length of tags in collections

- src/Table/MainTable/MainTable.js
- src/Table/Table.stories.js
- src/Table/useTableHook.js
When getting no results, the search string is URIencoded, and shows no default string if the emptystate-prop is not added. Small fix for this
Fixes https://github.com/asurgent/admin/issues/1020
> Fix for no results in table

- src/Tooltip/Tooltip.js
- src/Tooltip/helpers.js
The tooltip can get stuck when something in the children/DOM changes, like for example the button that's supposed to have the tooltip changes position on a click event; example go to http://localhost:3000/service-window?sw_q=w%20sort%3Astart-desc%20%20page%3A1 and expand a service window. Put the cursor on top of the gray circle of the caret-arrow to close it, and it's still there since the mouse is not longer on the button. Auto close the tooltop on children change.
Fixes https://github.com/asurgent/admin/issues/1048
> Change tooltip-comonent from class to func, and close on children-change

- src/Form/Form.stories.js
- src/Form/components/InputWrapper.js
- src/Form/components/InputWrapper.styled.js
- src/Form/hooks/helpers.js
- src/Form/types/Bool/Bool.js
- src/Form/types/DatePicker/DatePicker.js
- src/Form/types/Email/Email.js
- src/Form/types/FilterSelect/FilterSelect.js
- src/Form/types/FilterSelect/FilterSelect.styled.js
- src/Form/types/Number/Number.js
- src/Form/types/RadioGroup/RadioGroup.js
- src/Form/types/RadioGroup/RadioGroup.styled.js
- src/Form/types/Select/Select.js
- src/Form/types/Text/Text.js
- src/Form/types/TextArea/TextArea.js
- src/List/List.styled.js
Add a disabled property for formtypes (color, uneditable and cursor).
` someNumber: {
type: 'number',
...
},`
to
`someNumber: {
type: 'number',
...
disabled: true
}`
> Disabled prop for all formtypes

- package-lock.json
- src/Form/types/FilterSelect/FilterSelect.js
- src/Modal/Modal.stories.js
- src/Shield/OutsideEvent.js
- src/Shield/OutsideEvent.styled.js
- src/Shield/index.js
- src/Table/TableFilter/components/FilterCategory.js
There is an issue when using shield in a modal (same level and both uses z-index), so can only either use the shield (cant click on the dropdown), or not use the shield (can click on the dropdown but not close it). Fix for that by using a "click-outside-component" event handler that wraps the filter & filterselect. 
Fixes https://github.com/asurgent/admin/issues/1103
> Close on outside-click-type on shield

- src/Form/Form.stories.js
- src/Form/types/ObjectInput/InputWrapper.js
- src/Form/types/ObjectInput/Multiple/Multiple.js
- src/Form/types/ObjectInput/Single/Single.js
Numbers on object input was treated as a string, and add/remove changes didnt register on button clicks (had to do a change a field after the button clicks for the form to register as dirty).
> Number type fix & add/remove change event for multiple object form type

- src/Table/TableFilter/helpers.js
- src/Table/TableFilter/useFilterGroupHook.js
- src/Table/TableSearchBar/TableSearchBar.js
Fixes table-filer crash if regexp is inputed and not focusing on inputs in mobile
Fixes https://github.com/asurgent/admin/issues/1084
Fixes https://github.com/asurgent/admin/issues/1104
* You should be able to search for `/:(/` in a table-filter
* It should not focus on table-search-bar input if its a mobile device
> Tiny fixes

- src/Table/Table.stories.js
- src/Table/TableFilter/useFilterGroupHook.js
- src/Table/TableFilter/useFilterHook.js
When on an entity - service windows for example - the service window list can be filtered by entity_id initially, but that filters doesnt apply to the other filters in the table. So for example requested_by shows for all service windows, not just the one with the specific entity_id. Fix for that
> Background "invisible" filter applied to all other filters & mock story

- src/Form/Form.styled.js
When using autofill on form inputs it adds a default blueish color which looks weird on our inputs when using icons (plus is kinda unnessecary), so adding css to disable autofill coloring.
Fixes https://github.com/asurgent/admin/issues/1101
> Remove autofill background color on form inputs

- src/Button/Button.styled.js
- src/Table/BaseTable/BaseTable.styled.js
Expanded table to the edge with a padding so the hover state won't look cut off anymore. Added back borders on filter dropdown buttons in omnibar to make it look less busy when having a table inside an entity (Like tickets for at specific entity)
Fixes asurgent/admin#1152 (issue)
> Tojo table padding fix

- src/Form/Form.stories.js
- src/Form/types/Bool/Bool.js
- src/Form/types/Email/Email.js
- src/Form/types/RadioGroup/RadioGroup.js
- src/Form/types/Select/Select.js
- src/Form/types/Text/Text.js
- src/Form/types/TextArea/TextArea.js
- src/Form/types/TextMultiple/TextMultiple.js
When setting initial values with `Form.useFormBuilder({.... value: myValue` instead of adding it later in `useEffect(() => {
formData.updateFields([` some form types doesnt register the initial value because of `const [value, setValue] = useState('');` instead of `const [value, setValue] = useState(props.value || '');` . A fix for that
const formData = Form.useFormBuilder({`. The form should work as expected
> fix for initial setting of values on formtypes

- src/Form/types/Select/Select.js
Don't set a disabled option as selected in a select if there is no value set.
- Provide a optionslist with at least 2 options to a select-input. With the first option disabled. The select should not be provided any value.
- When you run the saga the SECOND option should be selected, not the first one, since its disabled.
> Default select correct select-option

- src/Block/components/SubnavigationBlock/SubnavigationBlock.js
- src/Table/BaseTable/helpers.js
Button has a prop called clearLocationState, but the table passes passLocationState, so it's never used. Added availiability to use clearLocationState on subnavigation menu too.
> button has clearLocationState but table passes passLocationState

- src/Button/Button.js
- src/Button/Button.stories.js
- src/Button/helper.js
- src/Table/TableFilter/components/TableFilter.js
setTableState prop for buttons that will override a state-key in the URL with a new encoded table-state value
```
const state = {
search: 'asd',
sort: 'timestamp-asc',
page: 1,
filter: {
timestamp: [['2121-12-12', 'eq']],
},
};
return (
<Button.Primary link="/123/12" setTableState={{ key: state }}>
Test link
</Button.Primary>
);
```
will produce a button with the HREF
`http://localhost:6006/123/12?key=asd%20sort%3Atimestamp-asc%20page%3A1%20filter%3AeyJ0aW1lc3RhbXAiOltbIjIxMjEtMTItMTIiLCJlcSJdXX0%3D`
And set the following state in the table
> Ability to set and override state-keys for tables

- src/Button/withStyle.js
- src/Graph/LineGraph/LineGraph.js
- src/Graph/components/Canvas/Canvas.js
- src/Graph/components/MarkerLine/MarkerLine.js
Made the `min/max` calculations take into markers into consideration even if the marker value is `0`
> Tiny graph fixes

- src/Block/Block.stories.js
- src/Block/index.js
Stadard blocks: 
Center,
Left,
Right,
Bordered,
Plain,
SpaceBetween,
Stretch,
Wrap,
WrapGrid,
behave a bit weird (probably missing css) after the big storybook update, so export them as we did before.
> Fix for standard block acting weird since storybook-update

- src/Graph/components/Canvas/useChartDimensions.js
- src/Table/TableFilter/components/TableFilter.styled.js
We get "ResizeObserver - loop limit exceeded" errors on sentry. 
"This error means that ResizeObserver was not able to deliver all observations within a single animation frame". By wrapping it in requestAnimationFrame you can limit the executions to a single frame"  - https://stackoverflow.com/questions/49384120/resizeobserver-loop-limit-exceeded
> Use requestAnimationFrame on resizeObserver to avoid errors

- src/Table/BaseTable/BaseTable.js
- src/Table/BaseTable/BaseTable.styled.js
- src/Table/Table.stories.js
Fixes https://github.com/asurgent/admin/issues/1199
> Option to show results without export button

- src/Graph/Heatmap/Heatmap.js
Don't add height of legend to total SVG-height if legend is not used
Related to: https://github.com/asurgent/cloudops-portal/pull/244
Fixes https://github.com/asurgent/admin/issues/1330
> Heatmap sizing bug if no legend

- src/Form/Form.stories.js
- src/Form/types/RadioGroup/RadioGroup.js
- src/Form/types/RadioGroup/RadioGroup.styled.js
Vertical radiogroup (old one had prop for it, but didn't work), and added some gap between the radios.
type: 'radiogroup',
label: 'Some Radio Group',
options: [
{ label: 'label1', value: 'value1' },
{ label: 'label2', value: 'value2' },
{ label: 'label3', value: 'value3' },
{ label: 'label4', value: 'value4' },
],
value: 'value2',
props: { vertical: true },
},` in Form.stories
> vertical radiogroup
